{% set version = "0.0.318" %}

package:
  name: metamorpheus
  version: {{ version }}

source:
  url: https://github.com/smith-chem-wisc/MetaMorpheus/releases/download/{{ version }}/MetaMorpheus_CommandLine.zip
  sha256: 6849984c6633aafc19d1e36716235f54c5ba2572e06333b012d34fd67196e224

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
  run:
    - dotnet-runtime <3.1.19

test:
  commands:
    - metamorpheus -g -o .

about:
  home: https://github.com/smith-chem-wisc/MetaMorpheus
  license: MIT
  license_file: LICENSE.txt
  summary: Proteomic search software with integrated calibration, PTM discovery, bottom-up, top-down and LFQ capabilities
  description: MetaMorpheus is a tool that was described in the Journal of Proteome Research, https://doi.org/10.1021/acs.jproteome.7b00873.
  dev_url: https://github.com/smith-chem-wisc/MetaMorpheus

extra:
  recipe-maintainers:
    - acesnik
