{% set version = "1.1.4" %}

package:
  name: metamorpheus
  version: {{ version }}

source:
  url: https://github.com/smith-chem-wisc/MetaMorpheus/releases/download/{{ version }}/MetaMorpheus_CommandLine.zip
  sha256: 7670a38dede7488d99b29eaa80c4788f3272fdde223c02fe5f4cec731961d088

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  run:
    - dotnet-runtime =8.0.6

test:
  commands:
    - metamorpheus -g -o .

about:
  home: https://github.com/smith-chem-wisc/MetaMorpheus
  license: MIT
  license_file: LICENSE.txt
  summary: Proteomic search software with integrated calibration, PTM discovery, bottom-up, top-down and LFQ capabilities
  description: MetaMorpheus is a tool that was described in the Journal of Proteome Research, https://doi.org/10.1021/acs.jproteome.7b00873.
  dev_url: https://github.com/smith-chem-wisc/MetaMorpheus

extra:
  recipe-maintainers:
    - acesnik
    - trishorts
