{% set version = "1.0.0" %}

package:
  name: metamorpheus
  version: {{ version }}

source:
  url: https://github.com/smith-chem-wisc/MetaMorpheus/releases/download/{{ version }}/MetaMorpheus_CommandLine.zip
  sha256: 07d9da0d14e02cd6fdcfd3da61d4027d0e32f5ebf6653e7d51932c77fd0651d1

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
  run:
    - dotnet-runtime =5.0

test:
  commands:
    - metamorpheus -g -o .

about:
  home: https://github.com/smith-chem-wisc/MetaMorpheus
  license: MIT
  license_file: LICENSE.txt
  summary: Proteomic search software with integrated calibration, PTM discovery, bottom-up, top-down and LFQ capabilities
  description: MetaMorpheus is a tool that was described in the Journal of Proteome Research, https://doi.org/10.1021/acs.jproteome.7b00873.
  dev_url: https://github.com/smith-chem-wisc/MetaMorpheus

extra:
  recipe-maintainers:
    - acesnik
