{% set version = "1.0.7" %}

package:
  name: metamorpheus
  version: {{ version }}

source:
  url: https://github.com/smith-chem-wisc/MetaMorpheus/releases/download/{{ version }}/MetaMorpheus_CommandLine.zip
  sha256: bf78782e5052cbb84efb0931a2d29cda9069f53768550f48e0206d022b94d038

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  run:
    - dotnet-runtime =8.0

test:
  commands:
    - metamorpheus -g -o .

about:
  home: https://github.com/smith-chem-wisc/MetaMorpheus
  license: MIT
  license_file: LICENSE.txt
  summary: Proteomic search software with integrated calibration, PTM discovery, bottom-up, top-down and LFQ capabilities
  description: MetaMorpheus is a tool that was described in the Journal of Proteome Research, https://doi.org/10.1021/acs.jproteome.7b00873.
  dev_url: https://github.com/smith-chem-wisc/MetaMorpheus

extra:
  recipe-maintainers:
    - acesnik
    - trishorts
